# Generated by Django 6.0 on 2025-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('photo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('salary', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Зарплата')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('about', models.TextField(verbose_name='О себе')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('interview', 'Назначено собеседование'), ('approved', 'Принят'), ('rejected', 'Отказ')], default='new', max_length=32, verbose_name='Статус')),
                ('level', models.CharField(choices=[('secondary', 'Среднее'), ('special', 'Среднее специальное'), ('higher', 'Высшее'), ('unhigher', 'Высшее неоконченное')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('grad_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
    ]
