# Generated by Django 6.0 on 2025-12-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Зарплата'),
        ),
    ]
